// app/api/javari/tools/github/write/selftest/route.ts
// Self-test for GitHub Write Tool (PR-only)

import { NextRequest, NextResponse } from 'next/server';
import { toolRegistry } from '@/lib/javari-tools-init';
import { githubWriteTool } from '@/lib/javari-github-write-tool';

export async function GET(request: NextRequest) {
  const results = {
    timestamp: new Date().toISOString(),
    tool_enabled: githubWriteTool.enabled(),
    tests: [] as any[],
    pr_url: null as string | null,
    overall: 'PENDING' as 'PASS' | 'FAIL' | 'PENDING',
  };

  // Register tool
  toolRegistry.registerTool(githubWriteTool);

  // Test 1: Check if tool is enabled
  results.tests.push({
    name: 'Tool Enabled Check',
    status: githubWriteTool.enabled() ? 'PASS' : 'FAIL',
    message: githubWriteTool.enabled() 
      ? 'GitHub Write Tool is enabled' 
      : 'GitHub Write Tool is disabled (check FEATURE_GITHUB_WRITE and GITHUB_WRITE_TOKEN)',
  });

  if (!githubWriteTool.enabled()) {
    results.overall = 'FAIL';
    return NextResponse.json(results);
  }

  const testBranch = `javari-selftest-${Date.now()}`;

  // Test 2: Create test branch
  try {
    const branchResult = await toolRegistry.executeTool('github_write', {
      action: 'createBranch',
      baseBranch: 'main',
      newBranch: testBranch,
    });

    results.tests.push({
      name: 'Create Test Branch',
      status: branchResult.success ? 'PASS' : 'FAIL',
      message: branchResult.success 
        ? `Created branch: ${testBranch}` 
        : branchResult.error,
      branch: branchResult.success ? branchResult.data?.name : undefined,
    });

    if (!branchResult.success) {
      results.overall = 'FAIL';
      return NextResponse.json(results);
    }

  } catch (error: any) {
    results.tests.push({
      name: 'Create Test Branch',
      status: 'FAIL',
      message: error.message,
    });
    results.overall = 'FAIL';
    return NextResponse.json(results);
  }

  // Test 3: Write harmless file
  try {
    const fileContent = `# Javari Self-Test
    
This file was created by Javari's autonomous self-test system.

Timestamp: ${new Date().toISOString()}
Test Branch: ${testBranch}

This file can be safely deleted.
`;

    const fileResult = await toolRegistry.executeTool('github_write', {
      action: 'upsertFile',
      path: 'javari_selftest.txt',
      content: fileContent,
      branch: testBranch,
      commitMessage: 'test: Javari self-test file',
    });

    results.tests.push({
      name: 'Write Test File',
      status: fileResult.success ? 'PASS' : 'FAIL',
      message: fileResult.success 
        ? 'Created javari_selftest.txt' 
        : fileResult.error,
      file_path: fileResult.success ? fileResult.data?.path : undefined,
    });

    if (!fileResult.success) {
      results.overall = 'FAIL';
      return NextResponse.json(results);
    }

  } catch (error: any) {
    results.tests.push({
      name: 'Write Test File',
      status: 'FAIL',
      message: error.message,
    });
    results.overall = 'FAIL';
    return NextResponse.json(results);
  }

  // Test 4: Create PR
  try {
    const prBody = `## Javari Self-Test PR

This PR was automatically created by Javari's self-test system.

### What Changed
- Added \`javari_selftest.txt\` test file

### Verification
This PR demonstrates:
- ✅ Branch creation
- ✅ File commit
- ✅ PR creation

### Rollback
Close this PR without merging. The branch can be safely deleted.

---
*Generated by Javari AI - ${new Date().toISOString()}*
`;

    const prResult = await toolRegistry.executeTool('github_write', {
      action: 'createPullRequest',
      branch: testBranch,
      title: `[Javari Self-Test] ${testBranch}`,
      body: prBody,
      baseBranch: 'main',
    });

    results.tests.push({
      name: 'Create Pull Request',
      status: prResult.success ? 'PASS' : 'FAIL',
      message: prResult.success 
        ? `Created PR #${prResult.data?.number}` 
        : prResult.error,
      pr_number: prResult.success ? prResult.data?.number : undefined,
    });

    if (prResult.success) {
      results.pr_url = prResult.data?.html_url || null;
    } else {
      results.overall = 'FAIL';
      return NextResponse.json(results);
    }

  } catch (error: any) {
    results.tests.push({
      name: 'Create Pull Request',
      status: 'FAIL',
      message: error.message,
    });
    results.overall = 'FAIL';
    return NextResponse.json(results);
  }

  // All tests passed
  results.overall = 'PASS';

  return NextResponse.json(results, {
    status: 200,
  });
}
