// lib/autonomy/taskSeeder.ts
// Purpose: Task seeder — converts CodeIssue[] from the intelligence engine into
//          properly formatted roadmap_tasks with embedded JSON issue payloads
//          for the repair_code executor. Deduplicates against existing tasks.
// Date: 2026-03-07

import { createClient }      from "@supabase/supabase-js";
import type { CodeIssue }    from "@/lib/intelligence/codeAnalyzer";
import type { JavariTarget } from "./targetRegistry";

// ── Types ──────────────────────────────────────────────════════════════════

export interface SeededTask {
  id         : string;
  title      : string;
  issueCount : number;
  severity   : string;
}

export interface SeedResult {
  tasksCreated: number;
  tasksSkipped: number;
  seededTasks : SeededTask[];
}

// ── Supabase ───────────────────────────────────────────────────────────────

function db() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL  ?? "",
    process.env.SUPABASE_SERVICE_ROLE_KEY ?? "",
    { auth: { persistSession: false } }
  );
}

// ── Issue grouping — one task per file for manageability ───────────────────

function groupIssuesByFile(issues: CodeIssue[]): Map<string, CodeIssue[]> {
  const groups = new Map<string, CodeIssue[]>();
  for (const issue of issues) {
    const existing = groups.get(issue.file) ?? [];
    existing.push(issue);
    groups.set(issue.file, existing);
  }
  return groups;
}

function topSeverity(issues: CodeIssue[]): CodeIssue["severity"] {
  const order = { critical: 0, high: 1, medium: 2, low: 3 };
  return issues.reduce((top, i) =>
    order[i.severity] < order[top] ? i.severity : top,
    "low" as CodeIssue["severity"]
  );
}

// ── Task row builder ───────────────────────────────────────────────────────

function buildRepairTask(
  file     : string,
  issues   : CodeIssue[],
  target   : JavariTarget,
  cycleId  : string
): Record<string, unknown> {
  const ts       = Date.now();
  const slug     = file.replace(/[^a-z0-9]/gi, "-").slice(0, 35).toLowerCase();
  const id       = `seed-repair-${slug}-${cycleId}`.slice(0, 80);
  const severity = topSeverity(issues);

  // Minimal CodeIssue[] serialised as JSON block inside description
  // The repair_code executor parses this to drive actual repairs
  const issuePayload = JSON.stringify(
    issues.map(i => ({
      severity     : i.severity,
      type         : i.type,
      file         : i.file,
      line         : i.line,
      description  : i.description,
      suggested_fix: i.suggested_fix,
      rule         : (i as CodeIssue & { rule?: string }).rule,
    })),
    null, 2
  );

  const title = `[REPAIR][${severity.toUpperCase()}] ${issues.length} issue${issues.length > 1 ? "s" : ""} in ${file}`;

  const description =
    `[type:ai_task] executor:repair_code\n` +
    `Automated repair task generated by Javari Engineering Loop.\n` +
    `Target: ${target.name} (${target.id})\n` +
    `File: ${file}\n` +
    `Severity: ${severity}\n` +
    `Issues: ${issues.length}\n` +
    `Cycle: ${cycleId}\n\n` +
    "```json\n" + issuePayload + "\n```";

  return {
    id,
    phase_id   : severity === "critical" || severity === "high" ? "security" : "maintenance",
    title,
    description,
    depends_on : [],
    status     : "pending",
    source     : "intelligence",
    updated_at : ts,
  };
}

// ── Main seeder ────────────────────────────────────────────────────────────

export async function seedRepairTasks(
  issues  : CodeIssue[],
  target  : JavariTarget,
  cycleId : string,
  options : {
    minSeverity?: "critical" | "high" | "medium" | "low";
    maxTasksPerCycle?: number;
  } = {}
): Promise<SeedResult> {
  const { minSeverity = "high", maxTasksPerCycle = 20 } = options;
  const SEVERITY_ORDER = { critical: 0, high: 1, medium: 2, low: 3 };
  const threshold = SEVERITY_ORDER[minSeverity];

  // Filter by minimum severity
  const actionable = issues.filter(
    i => SEVERITY_ORDER[i.severity] <= threshold
  );

  if (actionable.length === 0) {
    return { tasksCreated: 0, tasksSkipped: 0, seededTasks: [] };
  }

  // Group by file — one task per file
  const groups     = groupIssuesByFile(actionable);
  const rows: Record<string, unknown>[] = [];
  const seededMeta: SeededTask[] = [];

  let count = 0;
  for (const [file, fileIssues] of groups) {
    if (count >= maxTasksPerCycle) break;
    const row = buildRepairTask(file, fileIssues, target, cycleId);
    rows.push(row);
    seededMeta.push({
      id        : String(row.id),
      title     : String(row.title),
      issueCount: fileIssues.length,
      severity  : topSeverity(fileIssues),
    });
    count++;
  }

  // Deduplicate
  const { data: existing } = await db()
    .from("roadmap_tasks")
    .select("id")
    .in("id", rows.map(r => String(r.id)));
  const existingSet = new Set((existing ?? []).map((r: {id: string}) => r.id));
  const toInsert = rows.filter(r => !existingSet.has(String(r.id)));
  const skipped  = rows.length - toInsert.length;

  if (toInsert.length === 0) {
    return { tasksCreated: 0, tasksSkipped: skipped, seededTasks: [] };
  }

  const { error } = await db().from("roadmap_tasks").insert(toInsert);
  if (error) {
    console.error(`[taskSeeder] Insert failed: ${error.message}`);
    return { tasksCreated: 0, tasksSkipped: rows.length, seededTasks: [] };
  }

  console.log(`[taskSeeder] Seeded ${toInsert.length} repair tasks for ${target.name}`);
  return {
    tasksCreated: toInsert.length,
    tasksSkipped: skipped,
    seededTasks : seededMeta.filter(m => !existingSet.has(m.id)),
  };
}
