// lib/launch/first-module.ts
// CR AudioViz AI — First-Module Auto-Creation
// 2026-02-21 — STEP 9 Official Launch
//
// Generates a "Starter Workspace" module once per user via Module Factory.
// Tracks completion and prevents re-runs.

import { track } from "@/lib/analytics/track";
import { createLogger } from "@/lib/observability/logger";

const log = createLogger("factory");

// ── Types ─────────────────────────────────────────────────────────────────────

export interface StarterModuleResult {
  success:   boolean;
  alreadyRan: boolean;
  moduleId:  string;
  files:     StarterFile[];
  message:   string;
}

export interface StarterFile {
  path:    string;
  content: string;
  lines:   number;
}

// ── Sentinel key ─────────────────────────────────────────────────────────────
// Stored in Supabase user metadata to prevent re-runs

export const STARTER_MODULE_KEY = "starter_workspace_created";

// ── Starter module file templates ────────────────────────────────────────────

function buildStarterFiles(userId: string): StarterFile[] {
  const ts = new Date().toISOString();

  const files: StarterFile[] = [
    {
      path:    "app/starter/page.tsx",
      content: `// Starter Workspace — generated for user ${userId.slice(0, 8)}
// Generated: ${ts}
import { Zap } from "lucide-react";

export default function StarterPage() {
  return (
    <div className="min-h-screen bg-slate-950 flex items-center justify-center p-8">
      <div className="max-w-2xl w-full text-center space-y-6">
        <div className="w-16 h-16 mx-auto rounded-2xl bg-blue-600 flex items-center justify-center">
          <Zap className="w-8 h-8 text-white" />
        </div>
        <h1 className="text-3xl font-bold text-white">Your Starter Workspace</h1>
        <p className="text-slate-400 text-lg">
          This workspace was auto-generated by Javari AI.
          Customise it or use it as a foundation for your project.
        </p>
        <div className="grid grid-cols-2 gap-4 text-left">
          <div className="p-4 rounded-xl bg-slate-800 border border-slate-700">
            <h3 className="font-semibold text-white mb-1">✅ Module Factory</h3>
            <p className="text-slate-400 text-sm">Generate new modules in seconds.</p>
          </div>
          <div className="p-4 rounded-xl bg-slate-800 border border-slate-700">
            <h3 className="font-semibold text-white mb-1">🤖 Javari AI</h3>
            <p className="text-slate-400 text-sm">Autonomous AI that builds for you.</p>
          </div>
        </div>
        <a href="/store"
           className="inline-flex items-center gap-2 px-6 py-3 rounded-xl
                      bg-blue-600 hover:bg-blue-500 text-white font-semibold transition-all">
          Explore Module Store →
        </a>
      </div>
    </div>
  );
}`,
      lines: 38,
    },
    {
      path:    "app/starter/api/status/route.ts",
      content: `// Starter Workspace — Status API
// Generated: ${ts}
import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json({
    status:    "operational",
    module:    "starter_workspace",
    generated: "${ts}",
    version:   "1.0.0",
  });
}`,
      lines: 12,
    },
    {
      path:    "app/starter/components/StarterCard.tsx",
      content: `// Starter Workspace — Card Component
// Generated: ${ts}
interface StarterCardProps {
  title:       string;
  description: string;
  icon?:       string;
}

export function StarterCard({ title, description, icon = "✨" }: StarterCardProps) {
  return (
    <div className="p-5 rounded-xl bg-slate-800 border border-slate-700 hover:border-slate-600 transition-all">
      <div className="text-2xl mb-3">{icon}</div>
      <h3 className="font-semibold text-white mb-1">{title}</h3>
      <p className="text-slate-400 text-sm leading-relaxed">{description}</p>
    </div>
  );
}`,
      lines: 17,
    },
  ];

  return files;
}

// ── Main function ─────────────────────────────────────────────────────────────

export async function createFirstModule(
  userId:  string,
  options?: { force?: boolean }
): Promise<StarterModuleResult> {
  // Check if already created (via Supabase user metadata)
  if (!options?.force) {
    try {
      const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
      const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
      if (url && key) {
        const res = await fetch(`${url}/rest/v1/user_profiles?id=eq.${userId}&select=metadata`, {
          headers: { apikey: key, Authorization: `Bearer ${key}` },
        });
        if (res.ok) {
          const data = await res.json() as Array<{ metadata?: Record<string, unknown> }>;
          if (data[0]?.metadata?.[STARTER_MODULE_KEY]) {
            return {
              success: true, alreadyRan: true,
              moduleId: "starter_workspace", files: [],
              message: "Starter module already exists for this user",
            };
          }
        }
      }
    } catch {
      // Non-fatal — proceed with creation
    }
  }

  try {
    log.info("Creating starter module", { userId, meta: { userId: userId.slice(0, 8) } });

    const files = buildStarterFiles(userId);

    // Mark as created in user metadata
    try {
      const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
      const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
      if (url && key) {
        await fetch(`${url}/rest/v1/user_profiles?id=eq.${userId}`, {
          method:  "PATCH",
          headers: {
            apikey:          key,
            Authorization:   `Bearer ${key}`,
            "Content-Type":  "application/json",
            "Prefer":        "return=minimal",
          },
          body: JSON.stringify({ metadata: { [STARTER_MODULE_KEY]: new Date().toISOString() } }),
        });
      }
    } catch {
      // Non-fatal
    }

    // Track analytics
    track({
      event:   "module_install",
      userId,
      properties: {
        moduleId: "starter_workspace",
        tier:     "free",
        files:    files.length,
        auto:     true,
      },
    });

    log.info("Starter module created", {
      userId,
      meta: { files: files.length, paths: files.map((f) => f.path) },
    });

    return {
      success:    true,
      alreadyRan: false,
      moduleId:   "starter_workspace",
      files,
      message:    `Starter Workspace created with ${files.length} files`,
    };
  } catch (e) {
    const msg = e instanceof Error ? e.message : "Unknown error";
    log.error("Starter module creation failed", { meta: { error: msg } });
    return { success: false, alreadyRan: false, moduleId: "starter_workspace", files: [], message: msg };
  }
}
