-- docs/migrations/2026-03-10-build-artifacts.sql
-- Purpose: Creates the build_artifacts table for tracking all Javari AI autonomous builds.
--          Records every artifact generated: commit SHA, deployment URL, validator status.
-- Date: 2026-03-10

-- ── build_artifacts ──────────────────────────────────────────────────────────
-- One row per artifact generated by the autonomous ecosystem builder.

CREATE TABLE IF NOT EXISTS build_artifacts (
  artifact_id       uuid          PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id           text          NOT NULL,
  artifact_type     text          NOT NULL,
  repo              text          NOT NULL DEFAULT 'CR-AudioViz-AI/javari-ai',
  branch            text          NOT NULL DEFAULT 'main',
  commit_sha        text,
  deployment_url    text,
  status            text          NOT NULL DEFAULT 'pending',
  file_path         text,
  documentation     text,
  validation_notes  text,
  created_at        timestamptz   NOT NULL DEFAULT now()
);

-- Indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_build_artifacts_task_id
  ON build_artifacts (task_id);

CREATE INDEX IF NOT EXISTS idx_build_artifacts_status
  ON build_artifacts (status);

CREATE INDEX IF NOT EXISTS idx_build_artifacts_artifact_type
  ON build_artifacts (artifact_type);

CREATE INDEX IF NOT EXISTS idx_build_artifacts_created_at
  ON build_artifacts (created_at DESC);

-- status constraint — prevents invalid states
ALTER TABLE build_artifacts
  DROP CONSTRAINT IF EXISTS build_artifacts_status_check;

ALTER TABLE build_artifacts
  ADD CONSTRAINT build_artifacts_status_check
  CHECK (status IN (
    'pending',
    'building',
    'completed',
    'failed',
    'validation_failed',
    'deployed',
    'deployment_failed'
  ));

-- RLS — service role has full access; anon cannot read
ALTER TABLE build_artifacts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "service_role_all" ON build_artifacts;
CREATE POLICY "service_role_all"
  ON build_artifacts
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Summary view for dashboard queries
CREATE OR REPLACE VIEW build_artifacts_summary AS
SELECT
  artifact_type,
  status,
  COUNT(*)                                   AS count,
  COUNT(*) FILTER (WHERE commit_sha IS NOT NULL)    AS with_commits,
  COUNT(*) FILTER (WHERE deployment_url IS NOT NULL) AS with_deployments,
  MIN(created_at)                            AS first_seen,
  MAX(created_at)                            AS last_seen
FROM build_artifacts
GROUP BY artifact_type, status;
