// ─────────────────────────────────────────────────────────────────────────────
// Javari AI Engine — DO NOT MIX WITH PLATFORM LOGIC
// ─────────────────────────────────────────────────────────────────────────────
// lib/javari/team/execution-store.ts
// Javari TEAM Mode — Execution Persistence Layer
// Writes execution records and per-task results to Supabase.
// Uses supabaseAdmin (service-role) — bypasses RLS, server-side only.
// Never call from client components.
// Created: April 24, 2026
// Updated: April 24, 2026 — saveTaskResult uses upsert to prevent duplicate key errors on resume/replay

import { createAdminClient } from '@/lib/supabase/server'

const supabaseAdmin = createAdminClient()
import type { ExecutionPlan } from './execution-contract'
import type { TaskResult }    from './execution-engine'

// ─────────────────────────────────────────────────────────────────────────────
// Table name constants — single source of truth, no magic strings in callers
// ─────────────────────────────────────────────────────────────────────────────

const TABLE_EXECUTIONS      = 'javari_team_executions'
const TABLE_EXECUTION_TASKS = 'javari_team_execution_tasks'

// ─────────────────────────────────────────────────────────────────────────────
// Row types — mirror the logical table schemas exactly
// ─────────────────────────────────────────────────────────────────────────────

export interface ExecutionRow {
  id:           string   // uuid, generated by Supabase
  plan_id:      string
  status:       string   // 'pending' | 'running' | 'complete' | 'partial' | 'failed'
  total_cost:   number
  created_at:   string   // ISO timestamp
  finalized_at: string | null
}

export interface ExecutionTaskRow {
  id:           string   // uuid, generated by Supabase
  execution_id: string   // FK → javari_team_executions.id
  task_id:      string
  role:         string
  status:       string
  cost_used:    number
  output:       string | null
  error:        string | null
  started_at:   string
  completed_at: string
}

// ─────────────────────────────────────────────────────────────────────────────
// createExecution
// Inserts a new row into javari_team_executions at plan start.
// Status starts as 'running' — finalized later by finalizeExecution().
// Returns the generated execution UUID.
// ─────────────────────────────────────────────────────────────────────────────

export async function createExecution(plan: ExecutionPlan): Promise<string> {
  const { data, error } = await supabaseAdmin
    .from(TABLE_EXECUTIONS)
    .insert({
      plan_id:      plan.plan_id,
      status:       'running',
      total_cost:   0,           // updated on finalize
      created_at:   new Date().toISOString(),
      finalized_at: null,
    })
    .select('id')
    .single()

  if (error) {
    throw new Error(
      `execution-store.createExecution failed for plan "${plan.plan_id}": ${error.message} (code: ${error.code})`
    )
  }

  if (!data?.id) {
    throw new Error(
      `execution-store.createExecution: insert succeeded but no id returned for plan "${plan.plan_id}"`
    )
  }

  return data.id as string
}

// ─────────────────────────────────────────────────────────────────────────────
// saveTaskResult
// Upserts a single task result into javari_team_execution_tasks.
// Uses onConflict('execution_id,task_id') — if a row already exists for this
// execution + task combination (e.g. resume/replay with pre-seeded completed
// tasks), the existing row is updated instead of throwing a duplicate key error.
//
// Requires the composite unique constraint to be present on the table:
//   UNIQUE (execution_id, task_id)
// See SQL migration reference at the bottom of this file.
//
// Throws on any other DB error — callers must handle or the execution record stays dirty.
// ─────────────────────────────────────────────────────────────────────────────

export async function saveTaskResult(
  execution_id: string,
  task:         TaskResult,
  role:         string,
): Promise<void> {
  const { error } = await supabaseAdmin
    .from(TABLE_EXECUTION_TASKS)
    .upsert(
      {
        execution_id,
        task_id:      task.task_id,
        role,
        status:       task.status,
        cost_used:    task.cost_used,
        output:       task.output   ?? null,
        error:        task.error    ?? null,
        started_at:   task.started_at,
        completed_at: task.completed_at,
      },
      { onConflict: 'execution_id,task_id' }
    )

  if (error) {
    throw new Error(
      `execution-store.saveTaskResult failed for task "${task.task_id}" ` +
      `(execution: ${execution_id}): ${error.message} (code: ${error.code})`
    )
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// finalizeExecution
// Updates the execution row with final status + total_cost + finalized_at.
// Called once after executePlan() resolves, regardless of outcome.
// ─────────────────────────────────────────────────────────────────────────────

export async function finalizeExecution(
  execution_id: string,
  status:       'complete' | 'partial' | 'failed',
  total_cost:   number,
): Promise<void> {
  const { error } = await supabaseAdmin
    .from(TABLE_EXECUTIONS)
    .update({
      status,
      total_cost,
      finalized_at: new Date().toISOString(),
    })
    .eq('id', execution_id)

  if (error) {
    throw new Error(
      `execution-store.finalizeExecution failed for execution "${execution_id}": ` +
      `${error.message} (code: ${error.code})`
    )
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// getExecution
// Fetches a single execution row by id.
// Used by the API route and any future dashboard queries.
// ─────────────────────────────────────────────────────────────────────────────

export async function getExecution(execution_id: string): Promise<ExecutionRow> {
  const { data, error } = await supabaseAdmin
    .from(TABLE_EXECUTIONS)
    .select('*')
    .eq('id', execution_id)
    .single()

  if (error) {
    throw new Error(
      `execution-store.getExecution failed for id "${execution_id}": ${error.message} (code: ${error.code})`
    )
  }

  if (!data) {
    throw new Error(
      `execution-store.getExecution: no record found for id "${execution_id}"`
    )
  }

  return data as ExecutionRow
}

// ─────────────────────────────────────────────────────────────────────────────
// getExecutionTasks
// Fetches all task rows for a given execution, ordered by completed_at asc.
// ─────────────────────────────────────────────────────────────────────────────

export async function getExecutionTasks(execution_id: string): Promise<ExecutionTaskRow[]> {
  const { data, error } = await supabaseAdmin
    .from(TABLE_EXECUTION_TASKS)
    .select('*')
    .eq('execution_id', execution_id)
    .order('completed_at', { ascending: true })

  if (error) {
    throw new Error(
      `execution-store.getExecutionTasks failed for execution "${execution_id}": ` +
      `${error.message} (code: ${error.code})`
    )
  }

  return (data ?? []) as ExecutionTaskRow[]
}

// ─────────────────────────────────────────────────────────────────────────────
// SQL migration reference (DO NOT apply here — run in Supabase SQL editor)
// Project: kteobfyferrukqeolofj
// ─────────────────────────────────────────────────────────────────────────────
//
// -- Core tables (run first if not already present)
//
// create table if not exists javari_team_executions (
//   id           uuid primary key default gen_random_uuid(),
//   plan_id      text        not null,
//   status       text        not null default 'running',
//   total_cost   numeric     not null default 0,
//   created_at   timestamptz not null default now(),
//   finalized_at timestamptz
// );
//
// create table if not exists javari_team_execution_tasks (
//   id           uuid primary key default gen_random_uuid(),
//   execution_id uuid        not null references javari_team_executions(id) on delete cascade,
//   task_id      text        not null,
//   role         text        not null,
//   status       text        not null,
//   cost_used    numeric     not null default 0,
//   output       text,
//   error        text,
//   started_at   timestamptz not null,
//   completed_at timestamptz not null
// );
//
// create index if not exists idx_execution_tasks_execution_id
//   on javari_team_execution_tasks(execution_id);
//
// -- REQUIRED for upsert onConflict('execution_id,task_id') to work:
// -- Run this after creating the table if the constraint does not yet exist.
//
// alter table javari_team_execution_tasks
//   add constraint if not exists unique_execution_task
//   unique (execution_id, task_id);
