// lib/javari/roadmap/canonical-roadmap.ts
// JAVARI AI — CANONICAL MASTER ROADMAP V2.0
// Source: Master Roadmap V2.0 (R2 Canonical Set)
// Built from: 55 modules, 6 families, 11 platform layers
// Last Updated: 2026-02-19

import type { CanonicalRoadmap, Phase, Task, Milestone, Dependency, Risk, VerificationRequirement } from './canonical-types';

export const JAVARI_CANONICAL_ROADMAP: CanonicalRoadmap = {
  id: 'javari-os-v2',
  title: 'Javari AI — Full OS Operational Readiness',
  version: '2.0',
  objective: 'Activate Javari as a fully autonomous, self-healing AI operating system serving CR AudioViz AI platform across all 55 modules, 6 families, and 11 platform layers.',
  source: 'Master Roadmap V2.0 + R2 Canonical Set',
  createdAt: '2026-02-19T00:00:00Z',

  // ── PHASES ──────────────────────────────────────────────────────────────
  phases: [
    {
      id: 'phase-0',
      name: 'Platform Foundation',
      description: 'Fix Javari AI core, establish vault, deploy canonical knowledge, achieve stable baseline.',
      order: 0,
      status: 'active',
      estimatedDuration: '1–2 weeks',
      taskIds: [
        'task-p0-001', 'task-p0-002', 'task-p0-003',
        'task-p0-004', 'task-p0-005', 'task-p0-006',
      ],
      milestoneIds: ['milestone-0-complete'],
      exitCriteria: [
        'All 26 vault providers operational',
        'Javari chat responding <5s p95',
        'All 70 canonical R2 docs ingested',
        'TypeScript strict build passing 0 errors',
        'Roadmap engine activated and persisting state',
      ],
    },
    {
      id: 'phase-1',
      name: 'Module Factory Launch',
      description: 'Activate Module Factory for rapid module deployment. Launch first 10 revenue modules.',
      order: 1,
      status: 'pending',
      estimatedDuration: '2–4 weeks',
      taskIds: [
        'task-p1-001', 'task-p1-002', 'task-p1-003',
        'task-p1-004', 'task-p1-005',
      ],
      milestoneIds: ['milestone-1-revenue'],
      exitCriteria: [
        'Module Factory producing modules in <2 hours each',
        '10+ revenue modules live on craudiovizai.com',
        'Payment processing confirmed on all modules',
        'First paying customer acquired',
      ],
    },
    {
      id: 'phase-2',
      name: 'Platform Scaling',
      description: 'Scale to 55 modules, full games platform, CRAIverse virtual world foundation.',
      order: 2,
      status: 'pending',
      estimatedDuration: '4–8 weeks',
      taskIds: [
        'task-p2-001', 'task-p2-002', 'task-p2-003',
        'task-p2-004', 'task-p2-005', 'task-p2-006',
      ],
      milestoneIds: ['milestone-2-scale'],
      exitCriteria: [
        '55 modules deployed across all 6 families',
        'Games platform live with comprehensive library',
        'CRAIverse MVP launched',
        '$10K MRR achieved',
      ],
    },
    {
      id: 'phase-3',
      name: 'Autonomy & Intelligence',
      description: 'Javari reaches full self-healing, self-improving OS status. Grant targeting activated.',
      order: 3,
      status: 'pending',
      estimatedDuration: '4–6 weeks',
      taskIds: [
        'task-p3-001', 'task-p3-002', 'task-p3-003',
        'task-p3-004',
      ],
      milestoneIds: ['milestone-3-autonomous'],
      exitCriteria: [
        'Javari self-heals 95%+ of detected issues without human intervention',
        'Telemetry and eval systems operational',
        'First grant application submitted',
        '$100K ARR trajectory confirmed',
      ],
    },
    {
      id: 'phase-4',
      name: 'Enterprise & Growth',
      description: 'White-label solutions, mobile apps, international expansion, $1M ARR target.',
      order: 4,
      status: 'pending',
      estimatedDuration: '8–12 weeks',
      taskIds: [
        'task-p4-001', 'task-p4-002', 'task-p4-003',
      ],
      milestoneIds: ['milestone-4-million'],
      exitCriteria: [
        'First white-label enterprise client signed',
        'iOS + Android apps live',
        '$1M ARR achieved',
        'Grant funding received',
      ],
    },
  ],

  // ── TASKS ───────────────────────────────────────────────────────────────
  tasks: [
    // PHASE 0 — Foundation
    {
      id: 'task-p0-001',
      phaseId: 'phase-0',
      title: 'Complete R2 Canonical Ingestion (All 70 Docs)',
      description: 'Ingest all 70 canonical R2 documents into Supabase javari_knowledge with OpenAI embeddings. Currently 31/70 complete. Identify missing docs in R2 storage and trigger batch ingestion.',
      priority: 'critical',
      status: 'in-progress',
      provider: 'openai',
      estimatedHours: 2,
      dependencies: [],
      verificationCriteria: [
        'javari_knowledge table has 70+ R2 subcategories',
        '/api/javari/ingest-r2 reports 70+ docs ready',
        'Semantic search returns relevant results for all 7 test categories',
      ],
      tags: ['knowledge', 'r2', 'ingestion', 'foundation'],
    },
    {
      id: 'task-p0-002',
      phaseId: 'phase-0',
      title: 'Roadmap Engine — Persistent State (Supabase)',
      description: 'Replace in-memory RoadmapStateManager with Supabase-backed persistence. Tables javari_roadmaps and javari_tasks created. Update roadmap-state.ts to use Supabase CRUD.',
      priority: 'critical',
      status: 'in-progress',
      provider: 'anthropic',
      estimatedHours: 3,
      dependencies: [],
      verificationCriteria: [
        'javari_roadmaps table accessible via REST API',
        'javari_tasks table accessible via REST API',
        'Roadmap state survives Vercel cold start',
        '/api/javari/roadmap/status returns persisted state',
      ],
      tags: ['roadmap', 'persistence', 'supabase', 'foundation'],
    },
    {
      id: 'task-p0-003',
      phaseId: 'phase-0',
      title: 'Fix Perplexity API Key',
      description: 'Perplexity key ...kFGU returning 401 from production. Key was created Dec 2025 and hit rotation threshold. Generate new key at perplexity.ai/settings/api and update Vercel.',
      priority: 'high',
      status: 'blocked',
      provider: 'manual',
      estimatedHours: 0.25,
      dependencies: [],
      verificationCriteria: [
        '/api/test-providers shows perplexity: success',
        '/api/javari/providers shows perplexity OK',
      ],
      tags: ['credentials', 'perplexity', 'api-key'],
    },
    {
      id: 'task-p0-004',
      phaseId: 'phase-0',
      title: 'pgvector Index for Sub-3s Semantic Search',
      description: 'Current cosine similarity runs in JavaScript over 281 rows causing 15-19s latency on complex queries. Enable pgvector extension on Supabase, add vector index on javari_knowledge.embedding, convert TEXT embedding column to vector(1536).',
      priority: 'high',
      status: 'pending',
      provider: 'anthropic',
      estimatedHours: 4,
      dependencies: ['task-p0-001'],
      verificationCriteria: [
        'Supabase has pgvector extension enabled',
        'javari_knowledge.embedding column is vector(1536) type',
        'Semantic search latency <500ms for 1000+ row table',
        'Chat responses for canonical queries complete in <5s',
      ],
      tags: ['performance', 'pgvector', 'embeddings', 'supabase'],
    },
    {
      id: 'task-p0-005',
      phaseId: 'phase-0',
      title: 'Auto-Retry on Provider Failover',
      description: 'Chat route occasionally returns "temporarily unable to reach AI providers" on cold starts instead of retrying. Add exponential backoff retry (3 attempts, 500ms intervals) before returning error message.',
      priority: 'medium',
      status: 'pending',
      provider: 'anthropic',
      estimatedHours: 1,
      dependencies: [],
      verificationCriteria: [
        '100 sequential chat requests return 0 "unable to reach" messages',
        'Provider failover happens silently with successful response',
      ],
      tags: ['reliability', 'retry', 'failover', 'chat'],
    },
    {
      id: 'task-p0-006',
      phaseId: 'phase-0',
      title: 'Roadmap Activation — UI Dashboard',
      description: 'Build /roadmap page showing live phase progress, task status board, dependency graph visualization, and execution log. Update branding to Javari AI identity (avatar, colors, typography).',
      priority: 'high',
      status: 'pending',
      provider: 'anthropic',
      estimatedHours: 6,
      dependencies: ['task-p0-002'],
      verificationCriteria: [
        '/roadmap page loads and displays phase cards',
        'Task status updates in real-time',
        'Javari avatar (brunette, blue blazer) visible in header',
        'CR AudioViz AI brand colors applied (navy, neon-blue)',
      ],
      tags: ['ui', 'dashboard', 'branding', 'roadmap'],
    },

    // PHASE 1 — Module Factory
    {
      id: 'task-p1-001',
      phaseId: 'phase-1',
      title: 'Module Factory Core Engine',
      description: 'Build the Module Factory system that allows Javari to create new platform modules in <2 hours. Includes module scaffold generator, Supabase table provisioner, API route generator, and UI component factory.',
      priority: 'critical',
      status: 'pending',
      provider: 'openai',
      estimatedHours: 16,
      dependencies: ['task-p0-002', 'task-p0-006'],
      verificationCriteria: [
        'Module Factory creates fully functional module from natural language description',
        'New modules have Supabase tables, API routes, and UI within 2 hours',
        'Module registry updated automatically',
      ],
      tags: ['module-factory', 'automation', 'core'],
    },
    {
      id: 'task-p1-002',
      phaseId: 'phase-1',
      title: 'Launch Creative Suite Family (10 Modules)',
      description: 'Deploy first 10 revenue modules from Creative Suite family: Audio Visualizer, Voice Cloner, Image Generator, Video Creator, Logo Designer, Podcast Studio, Lyric Writer, Beat Maker, Subtitle Generator, Thumbnail Creator.',
      priority: 'critical',
      status: 'pending',
      provider: 'openai',
      estimatedHours: 40,
      dependencies: ['task-p1-001'],
      verificationCriteria: [
        'All 10 modules accessible on craudiovizai.com',
        'Each module processes user input and returns output',
        'Stripe payment required for premium usage',
        'Credit system deducted per use',
      ],
      tags: ['creative-suite', 'modules', 'revenue'],
    },
    {
      id: 'task-p1-003',
      phaseId: 'phase-1',
      title: 'Universal Credit System Integration',
      description: 'Connect all modules to the universal credit system. Credits never expire on paid plans. Auto-refund on errors. Complete code ownership rights for all outputs.',
      priority: 'high',
      status: 'pending',
      provider: 'anthropic',
      estimatedHours: 8,
      dependencies: ['task-p1-002'],
      verificationCriteria: [
        'Credits deducted correctly on each module use',
        'Error refunds process automatically within 60 seconds',
        'Credit balance visible in user dashboard',
        'Paid plan credits never expire (expiry field = null)',
      ],
      tags: ['credits', 'payments', 'integration'],
    },
    {
      id: 'task-p1-004',
      phaseId: 'phase-1',
      title: 'Amara AI — Training & Certification System',
      description: 'Deploy Amara AI as Training Delivery Officer. Launch 60+ certification programs across all platform families. Projected $2.5M first-year revenue from training ecosystem.',
      priority: 'high',
      status: 'pending',
      provider: 'anthropic',
      estimatedHours: 24,
      dependencies: ['task-p1-001'],
      verificationCriteria: [
        'Amara AI responds in her training persona',
        '10+ courses live and purchasable',
        'Certificate PDF generated on course completion',
        'Stripe payment for course enrollment works',
      ],
      tags: ['amara', 'training', 'certification', 'revenue'],
    },
    {
      id: 'task-p1-005',
      phaseId: 'phase-1',
      title: 'Affiliate & Monetization Activation',
      description: 'Activate all affiliate program integrations. Connect Awin (ID: 2692370), ElevenLabs PartnerStack (22% commission), and 300+ remaining alcohol programs for Javari Spirits. Update all Javari-branded app profiles.',
      priority: 'medium',
      status: 'pending',
      provider: 'openai',
      estimatedHours: 8,
      dependencies: ['task-p1-002'],
      verificationCriteria: [
        'Affiliate links tracked correctly in analytics',
        'Awin dashboard shows CR AudioViz AI program active',
        'Javari Spirits profile updated from CravBarrels branding',
        'Affiliate revenue visible in admin dashboard',
      ],
      tags: ['affiliate', 'monetization', 'revenue'],
    },

    // PHASE 2 — Platform Scaling
    {
      id: 'task-p2-001',
      phaseId: 'phase-2',
      title: 'All 6 Module Families Deployed (55 Modules)',
      description: 'Complete all 55 modules across 6 families: Creative Suite, Business Intelligence, Developer Tools, AI Integration, Social Impact, Gaming Platform. Use Module Factory for rapid deployment.',
      priority: 'critical',
      status: 'pending',
      provider: 'openai',
      estimatedHours: 80,
      dependencies: ['task-p1-001', 'task-p1-002'],
      verificationCriteria: [
        '55 modules deployed and functional',
        'All 6 family landing pages live',
        'Each module integrated with credit system',
        'Module performance <2s p95 response time',
      ],
      tags: ['modules', 'scaling', 'families'],
    },
    {
      id: 'task-p2-002',
      phaseId: 'phase-2',
      title: 'Games Platform Launch',
      description: 'Launch games platform with comprehensive game library. Categories include puzzle, strategy, arcade, educational, and social impact games. Credit system for premium games.',
      priority: 'high',
      status: 'pending',
      provider: 'openai',
      estimatedHours: 32,
      dependencies: ['task-p2-001'],
      verificationCriteria: [
        'Games platform accessible at /games',
        'Comprehensive game library live and playable',
        'Leaderboards functional',
        'Premium games require credits',
      ],
      tags: ['games', 'platform', 'entertainment'],
    },
    {
      id: 'task-p2-003',
      phaseId: 'phase-2',
      title: 'CRAIverse Virtual World — MVP',
      description: 'Launch CRAIverse MVP: avatar creation, virtual real estate, geographic community targeting for business marketing. Social impact modules for first responders, veterans, faith organizations, animal rescues.',
      priority: 'high',
      status: 'pending',
      provider: 'openai',
      estimatedHours: 48,
      dependencies: ['task-p2-001'],
      verificationCriteria: [
        'CRAIverse accessible at /craiverse',
        'Avatar creation wizard functional',
        '20 social impact modules operational',
        'Virtual real estate marketplace MVP live',
      ],
      tags: ['craiverse', 'virtual-world', 'social-impact'],
    },
    {
      id: 'task-p2-004',
      phaseId: 'phase-2',
      title: 'Grant Application Pipeline Activation',
      description: 'Activate grant application pipeline targeting $600M+ federal and private funding. Prepare SAM.gov registration for FEMA May 2026. Submit Google Cloud, NASE, AI Grant applications.',
      priority: 'high',
      status: 'pending',
      provider: 'anthropic',
      estimatedHours: 16,
      dependencies: ['task-p2-003'],
      verificationCriteria: [
        'SAM.gov registration complete',
        'Google Cloud grant application submitted',
        'NASE grant application submitted',
        'Grant tracking dashboard live in admin',
      ],
      tags: ['grants', 'funding', 'government'],
    },
    {
      id: 'task-p2-005',
      phaseId: 'phase-2',
      title: 'QNAP NAS Infrastructure Upgrade',
      description: 'Procure QNAP TVS-h874-i5-32G + 8×24TB=192TB storage (~$3,700). Deploy when revenue flowing. Repurpose Synology for document storage.',
      priority: 'low',
      status: 'pending',
      provider: 'manual',
      estimatedHours: 4,
      dependencies: ['task-p1-002'],
      verificationCriteria: [
        'QNAP NAS purchased and racked',
        '192TB storage pool formatted and mounted',
        'Synology repurposed for document archive',
        'Backup jobs configured',
      ],
      tags: ['infrastructure', 'storage', 'nas'],
    },
    {
      id: 'task-p2-006',
      phaseId: 'phase-2',
      title: 'Apple + Microsoft + LinkedIn OAuth',
      description: 'Add Apple OAuth ($99/yr — defer until revenue flowing), Microsoft OAuth, LinkedIn OAuth, Discord OAuth to authentication system.',
      priority: 'low',
      status: 'pending',
      provider: 'anthropic',
      estimatedHours: 8,
      dependencies: ['task-p1-002'],
      verificationCriteria: [
        'Apple Sign In functional (after $99 enrollment)',
        'Microsoft OAuth functional',
        'LinkedIn OAuth functional',
        'All new providers appear on login page',
      ],
      tags: ['oauth', 'authentication', 'social-login'],
    },

    // PHASE 3 — Autonomy
    {
      id: 'task-p3-001',
      phaseId: 'phase-3',
      title: 'Self-Healing Engine v2',
      description: 'Upgrade the 9 monitoring bots to active self-healing. When an issue is detected, Javari autonomously: diagnoses root cause, generates fix, tests in preview, deploys if tests pass, notifies Roy only on escalation.',
      priority: 'critical',
      status: 'pending',
      provider: 'anthropic',
      estimatedHours: 24,
      dependencies: ['task-p0-005', 'task-p2-001'],
      verificationCriteria: [
        '95%+ of P2/P3 issues self-healed without human intervention',
        'Auto-heal logs visible in admin dashboard',
        'Roy only notified for P0/P1 issues',
        'MTTR (mean time to repair) <5 minutes',
      ],
      tags: ['self-healing', 'autonomy', 'monitoring'],
    },
    {
      id: 'task-p3-002',
      phaseId: 'phase-3',
      title: 'Telemetry & Eval System',
      description: 'Implement full telemetry pipeline: PostHog for product analytics, Sentry for error tracking, UptimeRobot for availability. Add A/B testing infrastructure. Build eval harness for Javari response quality.',
      priority: 'high',
      status: 'pending',
      provider: 'openai',
      estimatedHours: 16,
      dependencies: ['task-p2-001'],
      verificationCriteria: [
        'PostHog capturing user events in production',
        'Sentry capturing and alerting on errors',
        'UptimeRobot monitoring all platform endpoints',
        'A/B test framework operational',
        'Javari eval scores tracked over time',
      ],
      tags: ['telemetry', 'analytics', 'monitoring', 'evals'],
    },
    {
      id: 'task-p3-003',
      phaseId: 'phase-3',
      title: 'Continuous Learning Pipeline',
      description: 'Javari learns from every interaction. Implement: conversation summarization to knowledge base, user feedback integration, error pattern learning, performance metric optimization.',
      priority: 'high',
      status: 'pending',
      provider: 'anthropic',
      estimatedHours: 20,
      dependencies: ['task-p3-002'],
      verificationCriteria: [
        'Conversation insights auto-ingested to javari_knowledge',
        'User feedback (thumbs up/down) influences provider routing',
        'Knowledge base grows automatically from platform activity',
        'Javari response quality improves measurably week-over-week',
      ],
      tags: ['learning', 'ai', 'continuous-improvement'],
    },
    {
      id: 'task-p3-004',
      phaseId: 'phase-3',
      title: 'Mobile App Development (iOS + Android)',
      description: 'Build React Native mobile apps for iOS and Android. Core features: Javari AI chat, module access, games, notifications, offline mode for key features.',
      priority: 'medium',
      status: 'pending',
      provider: 'openai',
      estimatedHours: 80,
      dependencies: ['task-p2-001'],
      verificationCriteria: [
        'iOS app submitted to App Store',
        'Android app submitted to Google Play',
        'Core Javari chat functional on mobile',
        'Push notifications operational',
      ],
      tags: ['mobile', 'ios', 'android', 'react-native'],
    },

    // PHASE 4 — Enterprise
    {
      id: 'task-p4-001',
      phaseId: 'phase-4',
      title: 'White-Label Enterprise Solution',
      description: 'Package the platform as white-label for enterprise clients. Custom branding, custom domain, dedicated Supabase project, SLA guarantees, dedicated support.',
      priority: 'high',
      status: 'pending',
      provider: 'anthropic',
      estimatedHours: 40,
      dependencies: ['task-p3-001', 'task-p2-001'],
      verificationCriteria: [
        'White-label provisioning system operational',
        'First enterprise client onboarded',
        'Custom domain + branding applied successfully',
        'Enterprise SLA dashboard live',
      ],
      tags: ['enterprise', 'white-label', 'revenue'],
    },
    {
      id: 'task-p4-002',
      phaseId: 'phase-4',
      title: 'International Expansion',
      description: 'Expand to key international markets: i18n for Spanish, Portuguese, French, and Mandarin. Local payment methods. GDPR compliance for EU.',
      priority: 'medium',
      status: 'pending',
      provider: 'openai',
      estimatedHours: 32,
      dependencies: ['task-p4-001'],
      verificationCriteria: [
        'Platform available in 5 languages',
        'Local payment methods configured',
        'GDPR compliance verified by legal',
        'International traffic being served correctly',
      ],
      tags: ['international', 'i18n', 'expansion'],
    },
    {
      id: 'task-p4-003',
      phaseId: 'phase-4',
      title: '$1M ARR Achievement',
      description: 'Reach $1M Annual Recurring Revenue within 14 months of platform launch. Track via 7 revenue streams: SaaS, marketplace, white-label, grants, affiliates, avatar services, merchandising.',
      priority: 'critical',
      status: 'pending',
      provider: 'manual',
      estimatedHours: 0,
      dependencies: ['task-p4-001', 'task-p3-001', 'task-p2-004'],
      verificationCriteria: [
        'MRR dashboard shows $83,333+/month ($1M ARR run rate)',
        'All 7 revenue streams contributing',
        'Grant funding received',
        'Investor deck updated with metrics',
      ],
      tags: ['revenue', 'milestone', 'arr'],
    },
  ],

  // ── MILESTONES ──────────────────────────────────────────────────────────
  milestones: [
    {
      id: 'milestone-0-complete',
      name: 'Platform Foundation Complete',
      phaseId: 'phase-0',
      description: 'All foundational systems operational. Javari AI fully deployed with 100% provider coverage, canonical knowledge ingested, roadmap engine live.',
      criteria: [
        '26/26 vault providers operational',
        '70/70 R2 canonical docs ingested',
        'Chat latency <5s p95',
        'Zero TypeScript build errors',
        'Roadmap persisted in Supabase',
      ],
    },
    {
      id: 'milestone-1-revenue',
      name: 'First Revenue',
      phaseId: 'phase-1',
      description: 'First paying customer on the platform. Module Factory operational.',
      criteria: [
        '10+ modules live',
        'First Stripe payment received',
        'Module Factory producing modules autonomously',
      ],
    },
    {
      id: 'milestone-2-scale',
      name: 'Platform at Scale',
      phaseId: 'phase-2',
      description: '55 modules across 6 families, games platform, CRAIverse MVP, $10K MRR.',
      criteria: [
        '55 modules deployed',
        'Games platform live',
        'CRAIverse MVP launched',
        '$10K MRR',
      ],
    },
    {
      id: 'milestone-3-autonomous',
      name: 'Javari Fully Autonomous',
      phaseId: 'phase-3',
      description: 'Javari self-heals, self-improves, and operates without human intervention for routine tasks.',
      criteria: [
        '95%+ self-heal rate',
        'Continuous learning pipeline operational',
        'First grant received',
      ],
    },
    {
      id: 'milestone-4-million',
      name: '$1M ARR',
      phaseId: 'phase-4',
      description: 'One million dollars in annual recurring revenue achieved within 14 months.',
      criteria: [
        '$83,333+/month MRR',
        'All 7 revenue streams active',
        'Enterprise clients signed',
      ],
    },
  ],

  // ── DEPENDENCIES ────────────────────────────────────────────────────────
  dependencies: [
    { from: 'task-p0-001', to: 'task-p0-004', type: 'enables' },
    { from: 'task-p0-002', to: 'task-p0-006', type: 'enables' },
    { from: 'task-p0-002', to: 'task-p1-001', type: 'enables' },
    { from: 'task-p1-001', to: 'task-p1-002', type: 'enables' },
    { from: 'task-p1-002', to: 'task-p1-003', type: 'enables' },
    { from: 'task-p1-001', to: 'task-p2-001', type: 'enables' },
    { from: 'task-p2-001', to: 'task-p2-002', type: 'enables' },
    { from: 'task-p2-001', to: 'task-p2-003', type: 'enables' },
    { from: 'task-p2-003', to: 'task-p2-004', type: 'enables' },
    { from: 'task-p2-001', to: 'task-p3-001', type: 'enables' },
    { from: 'task-p3-001', to: 'task-p4-001', type: 'enables' },
    { from: 'task-p3-002', to: 'task-p3-003', type: 'enables' },
  ],

  // ── RISKS ───────────────────────────────────────────────────────────────
  risks: [
    {
      id: 'risk-001',
      description: 'Vercel 30s function timeout limits complex autonomous execution tasks',
      severity: 'high',
      mitigation: 'Use Vercel Cron Jobs + Supabase background workers for long-running tasks. Queue system for tasks >20s.',
      affectedTaskIds: ['task-p3-001', 'task-p1-001'],
    },
    {
      id: 'risk-002',
      description: 'Perplexity API key expired — web research capability degraded',
      severity: 'medium',
      mitigation: 'Roy generates new key at perplexity.ai/settings/api. Fallback to Tavily for web search in the interim.',
      affectedTaskIds: ['task-p0-003'],
    },
    {
      id: 'risk-003',
      description: 'OpenAI API costs could escalate with autonomous module factory',
      severity: 'medium',
      mitigation: 'Implement cost caps per session. Route simple tasks to Groq (free tier). Monitor spend via admin dashboard.',
      affectedTaskIds: ['task-p1-001', 'task-p2-001'],
    },
    {
      id: 'risk-004',
      description: 'Supabase row limits at scale (500+ concurrent users)',
      severity: 'low',
      mitigation: 'Upgrade to Supabase Pro when approaching limits. Implement read replicas for analytics queries.',
      affectedTaskIds: ['task-p2-001'],
    },
  ],

  // ── RESOURCES ───────────────────────────────────────────────────────────
  resources: [
    { type: 'infrastructure', name: 'Vercel Pro', allocation: 'Active' },
    { type: 'infrastructure', name: 'Supabase (26 tables + growing)', allocation: 'Active' },
    { type: 'tool', name: 'Anthropic Claude (primary AI)', allocation: 'Active — $99.96 balance' },
    { type: 'tool', name: 'OpenAI GPT-4o (planning + embeddings)', allocation: 'Active' },
    { type: 'tool', name: 'Groq (fast free tier)', allocation: 'Active — 14,400 req/day' },
    { type: 'tool', name: 'Mistral (fast execution)', allocation: 'Active' },
    { type: 'tool', name: 'OpenRouter (meta-llama access)', allocation: 'Active' },
    { type: 'tool', name: 'ElevenLabs (voice)', allocation: 'Active' },
    { type: 'infrastructure', name: 'Stripe LIVE payments', allocation: 'Active' },
    { type: 'infrastructure', name: 'PayPal LIVE payments', allocation: 'Active' },
    { type: 'human', name: 'Roy Henderson (CEO)', allocation: 'Strategic direction + key decisions' },
    { type: 'human', name: 'Cindy Henderson (CMO)', allocation: 'Marketing + brand' },
    { type: 'tool', name: 'Javari AI (autonomous executor)', allocation: 'Primary development resource' },
  ],

  // ── VERIFICATION ────────────────────────────────────────────────────────
  verification: [
    {
      category: 'Identity',
      checks: [
        'Javari always responds as Javari, never as underlying model',
        'Identity invariants (name, creator, birthday, purpose) intact',
        'Avatar description (brunette, blue blazer, neon necklace) consistent',
        'Henderson Standard applied to all outputs',
      ],
    },
    {
      category: 'Knowledge',
      checks: [
        '70/70 R2 canonical docs ingested and retrievable',
        'Semantic search returns relevant context in <1s (after pgvector)',
        'No hallucinated facts about CR AudioViz AI platform',
        'Master Bible V7.0 content accurately recalled',
      ],
    },
    {
      category: 'Performance',
      checks: [
        'Chat responses <5s p95',
        'Provider failover transparent to users',
        'Zero cold-start failures visible to users',
        'All 26 vault providers accessible',
      ],
    },
    {
      category: 'Autonomy',
      checks: [
        'Roadmap state persists across Vercel cold starts',
        'Task engine can pick up execution after restart',
        'Self-healing bots operational (9 active)',
        'Continuous learning pipeline ingesting new knowledge',
      ],
    },
    {
      category: 'Revenue',
      checks: [
        'Stripe payment flow functional end-to-end',
        'PayPal payment flow functional end-to-end',
        'Credit system correctly deducting and refunding',
        'All active modules processing payments',
      ],
    },
  ],
};
