// app/(public)/legal/terms/page.tsx
// CR AudioViz AI — Terms of Service
// 2026-02-21 — STEP 8 Go-Live

import { Metadata } from "next";
import { BRAND_IDENTITY } from "@/lib/brand/tokens";
import LegalLayout from "../LegalLayout";

export const metadata: Metadata = {
  title: "Terms of Service — CR AudioViz AI",
  description: "The terms governing your use of CR AudioViz AI and Javari AI platform.",
};

export default function TermsPage() {
  return (
    <LegalLayout title="Terms of Service" lastUpdated="February 21, 2026">

      <section>
        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing or using the CR AudioViz AI platform and Javari AI services
          (&ldquo;Service&rdquo;), you agree to be bound by these Terms of Service
          (&ldquo;Terms&rdquo;). If you do not agree to these Terms, do not use our Service.
          These Terms constitute a legally binding agreement between you and CR AudioViz AI, LLC.
        </p>
      </section>

      <section>
        <h2>2. Service Description</h2>
        <p>
          CR AudioViz AI provides an AI-powered creative platform including Javari AI assistant,
          Module Factory, multi-agent orchestration, and associated tools. The Service is provided
          on an as-is, as-available basis. We reserve the right to modify, suspend, or discontinue
          any aspect of the Service at any time.
        </p>
      </section>

      <section>
        <h2>3. Account Responsibilities</h2>
        <ul>
          <li>You must be at least 13 years old to use the Service</li>
          <li>You are responsible for maintaining the security of your account credentials</li>
          <li>You must provide accurate and complete registration information</li>
          <li>You are responsible for all activity that occurs under your account</li>
          <li>You must notify us immediately of any unauthorized account access</li>
        </ul>
      </section>

      <section>
        <h2>4. Acceptable Use</h2>
        <p>You agree not to use the Service to:</p>
        <ul>
          <li>Violate any applicable laws or regulations</li>
          <li>Generate, distribute, or facilitate harmful, abusive, or illegal content</li>
          <li>Attempt to circumvent our security systems or rate limits</li>
          <li>Engage in unauthorized scraping, crawling, or data extraction</li>
          <li>Impersonate others or misrepresent your identity</li>
          <li>Interfere with or disrupt the integrity or performance of the Service</li>
          <li>Develop competing products using our proprietary AI systems without authorization</li>
        </ul>
      </section>

      <section>
        <h2>5. Credits & Billing</h2>
        <p>
          Our Service operates on a credit-based system. Credits purchased on paid plans
          <strong> never expire</strong> while your subscription is active. Free-tier credits
          reset monthly. Subscription fees are billed monthly or annually in advance.
          All sales are final; refunds are issued at our discretion for documented technical failures.
        </p>
        <p>
          Automatic error-compensation credits will be applied to your account if our systems cause
          documented request failures. This is our service guarantee.
        </p>
      </section>

      <section>
        <h2>6. Intellectual Property</h2>
        <p>
          <strong>Your content:</strong> You retain ownership of all content you create using our
          Service. Code generated by our Module Factory is yours to use, modify, and deploy — you
          receive complete ownership rights as described in our &ldquo;Build Here, Host Anywhere&rdquo;
          philosophy.
        </p>
        <p>
          <strong>Our platform:</strong> The Service, including all underlying technology, is owned
          by CR AudioViz AI, LLC and protected by intellectual property laws. You may not copy,
          reverse-engineer, or create derivative works of our platform.
        </p>
      </section>

      <section>
        <h2>7. Limitation of Liability</h2>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, CR AUDIOVIZ AI SHALL NOT BE LIABLE FOR
          INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOST PROFITS,
          ARISING OUT OF OR RELATING TO YOUR USE OF THE SERVICE. OUR TOTAL LIABILITY SHALL NOT EXCEED
          THE AMOUNT PAID BY YOU IN THE TWELVE MONTHS PRECEDING THE CLAIM.
        </p>
      </section>

      <section>
        <h2>8. Disclaimer of Warranties</h2>
        <p>
          THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR
          IMPLIED. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE
          FROM HARMFUL COMPONENTS. AI-GENERATED CONTENT MAY CONTAIN ERRORS AND SHOULD BE REVIEWED
          BEFORE PROFESSIONAL OR CRITICAL USE.
        </p>
      </section>

      <section>
        <h2>9. Termination</h2>
        <p>
          Either party may terminate these Terms at any time. We may suspend or terminate your
          account for violations of these Terms without prior notice. Upon termination, your right
          to use the Service ceases and unused credits are forfeited (except where prohibited by law).
        </p>
      </section>

      <section>
        <h2>10. Governing Law</h2>
        <p>
          These Terms are governed by the laws of the State of Florida, United States, without
          regard to conflict of law principles. Disputes shall be resolved through binding
          arbitration in Fort Myers, Florida, except for claims eligible for small claims court.
        </p>
      </section>

      <section>
        <h2>11. Changes to Terms</h2>
        <p>
          We reserve the right to modify these Terms. We will provide at least 30 days&apos; notice
          for material changes via email and in-platform notification. Continued use after the
          effective date constitutes acceptance of the new Terms.
        </p>
      </section>

      <section>
        <h2>12. Contact</h2>
        <p>
          For questions about these Terms:<br />
          <strong>CR AudioViz AI, LLC</strong><br />
          Fort Myers, Florida, United States<br />
          Email: <a href={`mailto:${BRAND_IDENTITY.support}`}>{BRAND_IDENTITY.support}</a>
        </p>
      </section>

    </LegalLayout>
  );
}
