// lib/auth/config.ts — CR AudioViz AI | 2026-03-11
// Auth configuration stub — generated by stabilization fix
import type { NextAuthOptions } from 'next-auth';

export const authOptions: NextAuthOptions = {
  providers: [],
  session: { strategy: 'jwt' },
};

export default authOptions;
